# CWE static analyzer demo commands.
# Install on Arch/Crostini: sudo pacman -S just python souffle

set shell := ["bash", "-cu"]

src := "samples"
analysis_dir := "analysis"
facts_dir := "analysis/facts"
datalog_dir := "analysis/datalog"
findings_json := "analysis/findings.json"
report_md := "analysis/report.md"
sarif := "analysis/custom-cwe.sarif"
repair_dir := "analysis/repair"
repair_md := "analysis/repair/gemma_diff_suggestions.md"
repair_json := "analysis/repair/gemma_diff_suggestions.json"
repair_patch := "analysis/repair/suggested.patch"

# Show available commands
_default:
    @just --list

# Install local Arch dependencies used in the live demo
setup-arch:
    sudo pacman -S --needed python just souffle

# Extract source facts only. This is the Python/AST/regex front-end.
facts:
    mkdir -p {{facts_dir}}
    python scripts/extract_facts.py {{src}} --facts {{facts_dir}}

# Run only the Souffle formal inference layer. Requires `souffle` on PATH.
infer: facts
    mkdir -p {{datalog_dir}}
    souffle -F {{facts_dir}} -D {{datalog_dir}} rules/cwe_rules.dl
    cat {{datalog_dir}}/finding.csv

# Convert existing finding.csv into JSON, Markdown and SARIF.
render:
    python scripts/facts_to_results.py --facts {{facts_dir}} --datalog {{datalog_dir}}/finding.csv --json {{findings_json}} --markdown {{report_md}} --sarif {{sarif}}

# Full pipeline: facts -> Souffle if installed -> Python fallback if not -> JSON/Markdown/SARIF.
analyze:
    mkdir -p {{analysis_dir}} {{datalog_dir}}
    python scripts/analyze_cwe.py {{src}} --json {{findings_json}} --markdown {{report_md}} --sarif {{sarif}} --facts {{facts_dir}} --datalog {{datalog_dir}} || true

# Force fallback for machines without Souffle or for comparing outputs.
analyze-fallback:
    mkdir -p {{analysis_dir}} {{datalog_dir}}
    python scripts/analyze_cwe.py {{src}} --no-souffle --json {{findings_json}} --markdown {{report_md}} --sarif {{sarif}} --facts {{facts_dir}} --datalog {{datalog_dir}} || true

# Print the Markdown report generated by the analyzer
report: analyze
    cat {{report_md}}

# Run Souffle Datalog inference over generated facts and render reports.
souffle: facts
    mkdir -p {{datalog_dir}}
    souffle -F {{facts_dir}} -D {{datalog_dir}} rules/cwe_rules.dl
    cat {{datalog_dir}}/finding.csv
    python scripts/facts_to_results.py --facts {{facts_dir}} --datalog {{datalog_dir}}/finding.csv --json {{findings_json}} --markdown {{report_md}} --sarif {{sarif}}

# Generate or print a Gemini/Gemma prompt/report. Set GEMINI_API_KEY for API mode; GEMINI_MODEL defaults to gemma-4-31b-it.
gemini: analyze
    if ! python scripts/gemini_summarize.py {{findings_json}} > analysis/gemini_report.md; then \
      echo "# Gemini/Gemma report" > analysis/gemini_report.md; \
      echo >> analysis/gemini_report.md; \
      echo "Gemini/Gemma API failed, but the static analyzer artifacts were generated successfully. Check the job log for API details." >> analysis/gemini_report.md; \
    fi
    cat analysis/gemini_report.md

# Generate Gemma/Gemini unified-diff suggestions for classroom summary display.
# This does not apply patches and does not create a PR.
repair-demo: analyze
    mkdir -p {{repair_dir}}
    if ! python scripts/gemma_diff_suggest.py {{findings_json}} --src {{src}} --out-md {{repair_md}} --out-json {{repair_json}} --out-patch {{repair_patch}}; then \
      echo "# Gemma Diff Suggestions" > {{repair_md}}; \
      echo >> {{repair_md}}; \
      echo "Gemma/Gemini diff generation failed, but static analysis completed successfully. Check the job log for API details." >> {{repair_md}}; \
      : > {{repair_patch}}; \
      echo '{"title":"Gemma Diff Suggestions","summary":"generation failed","patches":[]}' > {{repair_json}}; \
    fi
    cat {{repair_md}}

# One-command classroom demo: report + formal facts + inferred findings.
demo: analyze
    @echo "\n===== CWE Markdown Report ====="
    cat {{report_md}}
    @echo "\n===== Extracted Facts Manifest ====="
    cat {{facts_dir}}/manifest.json
    @echo "\n===== Inferred Findings Relation ====="
    cat {{datalog_dir}}/finding.csv

# Remove generated analysis outputs
clean:
    rm -rf {{findings_json}} {{sarif}} {{report_md}} {{facts_dir}} {{datalog_dir}} analysis/gemini_report.md {{repair_dir}}

# Check that generated SARIF exists and is non-empty
check: analyze
    test -s {{sarif}}
    test -s {{findings_json}}
    test -s {{datalog_dir}}/finding.csv
    python -m json.tool {{findings_json}} >/dev/null
