# CWE static analyzer demo commands.
# Install on Arch/Crostini: sudo pacman -S just

set shell := ["bash", "-cu"]

src := "samples"
analysis_dir := "analysis"
facts_dir := "analysis/facts"
datalog_dir := "analysis/datalog"
findings_json := "analysis/findings.json"
report_md := "analysis/report.md"
sarif := "analysis/custom-cwe.sarif"

# Show available commands
_default:
    @just --list

# Install local Arch dependencies used in the live demo
setup-arch:
    sudo pacman -S --needed python just souffle

# Run the coursework CWE analyzer and generate JSON, Markdown, SARIF, and Souffle facts
analyze:
    mkdir -p {{analysis_dir}}
    python scripts/analyze_cwe.py {{src}} --json {{findings_json}} --markdown {{report_md}} --sarif {{sarif}} --facts {{facts_dir}} || true

# Print the Markdown report generated by the analyzer
report: analyze
    cat {{report_md}}

# Run Souffle Datalog inference over generated facts
souffle: analyze
    mkdir -p {{datalog_dir}}
    souffle -F {{facts_dir}} -D {{datalog_dir}} rules/cwe_rules.dl
    cat {{datalog_dir}}/finding.csv

# Generate or print a Gemini prompt/report. Set GEMINI_API_KEY for API mode.
gemini: analyze
    python scripts/gemini_summarize.py {{findings_json}} > analysis/gemini_report.md
    cat analysis/gemini_report.md

# One-command classroom demo: analyzer report + Datalog result
demo: analyze
    @echo "\n===== CWE Markdown Report ====="
    cat {{report_md}}
    @echo "\n===== Souffle Datalog Findings ====="
    mkdir -p {{datalog_dir}}
    souffle -F {{facts_dir}} -D {{datalog_dir}} rules/cwe_rules.dl
    cat {{datalog_dir}}/finding.csv

# Remove generated analysis outputs
clean:
    rm -rf {{findings_json}} {{sarif}} {{report_md}} {{facts_dir}} {{datalog_dir}} analysis/gemini_report.md

# Check that generated SARIF exists and is non-empty
check: analyze
    test -s {{sarif}}
    test -s {{findings_json}}
    python -m json.tool {{findings_json}} >/dev/null
